server:
  port: 8769
zuul:
  routes:
    api-sp: # 负载均衡默认是轮训方式
      path: /api-sp/**
      serviceId: service-provider
    api-sf:
      path: /api-sf/**
      serviceId: service-feign
spring:
  rabbitmq: # 消息总线需要
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@server1:8761/eureka/,http://admin:123456@server2:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）