server:
  port: 8090
feign:
  hystrix:
    enabled: true # 开启断路由
spring:
  rabbitmq: # 消息总线需要
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@server1:8761/eureka/,http://admin:123456@server2:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）